# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_1(object):
    def setupUi(self, MainWindow_1):
        MainWindow_1.setObjectName("MainWindow_1")
        MainWindow_1.resize(160, 210)
        MainWindow_1.setMinimumSize(QtCore.QSize(160, 210))
        MainWindow_1.setMaximumSize(QtCore.QSize(160, 210))
        self.centralwidget = QtWidgets.QWidget(MainWindow_1)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setStyleSheet("")
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout.addWidget(self.label_1)
        self.lE_coeff_resist = QtWidgets.QLineEdit(self.centralwidget)
        self.lE_coeff_resist.setObjectName("lE_coeff_resist")
        self.horizontalLayout.addWidget(self.lE_coeff_resist)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lE_start_v = QtWidgets.QLineEdit(self.centralwidget)
        self.lE_start_v.setObjectName("lE_start_v")
        self.horizontalLayout_2.addWidget(self.lE_start_v)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lE_angle = QtWidgets.QLineEdit(self.centralwidget)
        self.lE_angle.setPlaceholderText("")
        self.lE_angle.setObjectName("lE_angle")
        self.horizontalLayout_3.addWidget(self.lE_angle)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lE_height = QtWidgets.QLineEdit(self.centralwidget)
        self.lE_height.setObjectName("lE_height")
        self.horizontalLayout_4.addWidget(self.lE_height)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.btn_image = QtWidgets.QPushButton(self.centralwidget)
        self.btn_image.setObjectName("btn_image")
        self.verticalLayout.addWidget(self.btn_image)
        self.btn_spec_mode = QtWidgets.QPushButton(self.centralwidget)
        self.btn_spec_mode.setObjectName("btn_spec_mode")
        self.verticalLayout.addWidget(self.btn_spec_mode)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow_1.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_1)

    def retranslateUi(self, MainWindow_1):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_1.setWindowTitle(_translate("MainWindow_1", "Menu"))
        self.comboBox.setItemText(0, _translate("MainWindow_1", "Без силы трения"))
        self.comboBox.setItemText(1, _translate("MainWindow_1", "С учетом силы трения"))
        self.label_1.setText(_translate("MainWindow_1", "K:"))
        self.lE_coeff_resist.setText(_translate("MainWindow_1", "0.9"))
        self.label_2.setText(_translate("MainWindow_1", "v_0:"))
        self.lE_start_v.setText(_translate("MainWindow_1", "10"))
        self.label_3.setText(_translate("MainWindow_1", "angle:"))
        self.lE_angle.setText(_translate("MainWindow_1", "60"))
        self.label_4.setText(_translate("MainWindow_1", "height:"))
        self.lE_height.setText(_translate("MainWindow_1", "20"))
        self.btn_image.setText(_translate("MainWindow_1", "image"))
        self.btn_spec_mode.setText(_translate("MainWindow_1", "spec_mode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_1 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_1()
    ui.setupUi(MainWindow_1)
    MainWindow_1.show()
    sys.exit(app.exec_())
